name: sample_2pop
setup_name: minimal
start_date: 2020-01-31
end_date: 2020-05-31
data_path: data
nslots: 1

spatial_setup:
  geodata: geodata_sample_2pop.csv
  mobility: mobility_sample_2pop.csv

seeding:
  method: FolderDraw
  lambda_file: data/seeding.csv
  date_sd: 0
  amount_sd: 0

compartments:
  infection_stage: ["S", "E", "I", "R"]

seir:
  integration:
    method: rk4
    dt: 1 / 10
    stoch_traj_flag: 0
  parameters:
    sigma:
      value:
        distribution: fixed
        value: 1 / 4
    gamma:
      value:
        distribution: fixed
        value: 1 / 5
    Ro:
      value:
        distribution: uniform
        low: 2
        high: 3
  transitions:
    - source: ["S"]
      destination: ["E"]
      rate: ["Ro * gamma"]
      proportional_to: [["S"],["I"]]
      proportion_exponent: ["1"]
    - source: ["E"]
      destination: ["I"]
      rate: ["sigma"]
      proportional_to: ["E"]
      proportion_exponent: ["1"]
    - source: ["I"]
      destination: ["R"]
      rate: ["gamma"]
      proportional_to: ["I"]
      proportion_exponent: ["1"]

interventions:
  scenarios:
    - None
  settings:
    None:
      template: SinglePeriodModifier
      parameter: r0
      period_start_date: 2020-04-01
      period_end_date: 2020-05-15
      value:
        distribution: fixed
        value: 0

outcomes:
  method: delayframe
  scenarios:
    - None
  settings:
    None:
      incidI:
        source:
          incidence:
            infection_stage: "I1"
        probability:
          value:
            distribution: fixed
            value: 1
        delay:
          value:
            distribution: fixed
            value: 0

inference:
  iterations_per_slot: 1
  do_inference: FALSE
