name: sample_2pop
setup_name: minimal
start_date: 2020-01-31
end_date: 2020-08-31
data_path: data
nslots: 1

spatial_setup:
  geodata: geodata_sample_2pop.csv
  mobility: mobility_sample_2pop.csv
  popnodes: population
  nodenames: province_name

seeding:
  method: FromFile
  seeding_file: data/seeding_2pop_2var.csv

inital_conditions:
  method: FromFile
  initial_conditions_file: data/ic_2pop_2var.csv

compartments:
  infection_stage: ["S", "E", "I", "R"]
  variant: ["A","B"]

seir:
  integration:
    method: rk4
    dt: 1 / 10
  parameters:
    # 1/sigma = duration of exposed period
    sigma:
      value:
        distribution: fixed
        value: 1 / 4
    # 1/gamma = duration of infectious period
    gamma:
      value:
        distribution: fixed
        value: 1 / 5
    # B = R0 * gamma
    Ro:
      value:
        distribution: uniform
        low: 2
        high: 3
    # relative transmission advantage of variant B
    fB:
        value:
            distribution: fixed
            value: 1.5
    # immune escape efficacy of variant B (vs variant A)
    eB:
        value:
            distribution: fixed
            value: 0.5
  transitions:
    # new infections of susceptible individuals
    - source: [["S"],["A","B"]]
      destination: [["E"],["A","B"]]]
      rate: [["Ro * gamma"],["1","fB"]]
      proportional_to: ["source",[["I",["A","B"]]]]
      proportion_exponent: ["1","1"]
    # progression of exposed infections
    - source: [["E"],["A","B"]]
      destination: [["I"],["A","B"]]
      rate: [["sigma"],["1","1"]] 
      proportional_to: ["source"]
      proportion_exponent: ["1"]
    # recovery from infection
    - source: [["I"],["A","B"]]
      destination: [["R"],["A","B"]]
      rate: [["gamma"],["1","1"]] 
      proportional_to: ["source"]
      proportion_exponent: ["1"]
    # infections of individuals previously infected with variant B with variant A
    - source: [["R"],["A"]]
      destination: [["E"],["B"]]
      rate: [["Ro * gamma"],["fB * eB"]]
      proportional_to: ["source"]
      proportional_exponent: ["1"]

interventions:
  scenarios:
    - None
  settings:
    None:
      template: Reduce
      parameter: r0
      period_start_date: 2020-04-01
      period_end_date: 2020-05-15
      value:
        distribution: fixed
        value: 0

