name: sample_2pop
setup_name: minimal
start_date: 2020-04-01
end_date: 2020-05-31
data_path: model_input
nslots: 1

subpop_setup:
  geodata: geodata_sample_2pop.csv
  mobility: mobility_sample_2pop.csv

initial_conditions:
  method: FromFile
  # take the output from another model run (which started on 2020-01-31) on start_date
  initial_conditions_file: model_input/model_output_example/sample_2pop/20231018_133013/seir/000000001.20231018_133013.seir.parquet
  allow_missing_nodes: FALSE
  allow_missing_compartments: FALSE

compartments:
  infection_stage: ["S", "E", "I", "R"]

seir:
  integration:
    method: rk4
    dt: 1
  parameters:
    sigma:
      value: 1 / 4
    gamma:
      value: 1 / 5
    Ro:
      value: 3
  transitions:
    - source: ["S"]
      destination: ["E"]
      rate: ["Ro * gamma"]
      proportional_to: [["S"],["I"]]
      proportion_exponent: ["1","1"]
    - source: ["E"]
      destination: ["I"]
      rate: ["sigma"]
      proportional_to: ["E"]
      proportion_exponent: ["1"]
    - source: ["I"]
      destination: ["R"]
      rate: ["gamma"]
      proportional_to: ["I"]
      proportion_exponent: ["1"]

